apiVersion: v1
kind: ServiceAccount
metadata:
  name: memguardian
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: memguardian
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  - "metrics.k8s.io"
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - "apps"
  resources:
  - replicasets/status 
  verbs:
  - get 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memguardian-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memguardian
subjects:
- kind: ServiceAccount
  name: memguardian
  namespace: default

